# Generated by Django 3.0.4 on 2020-04-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.IntegerField(choices=[(1, '大学一年级'), (2, '大学二年级'), (3, '大学三年级'), (4, '大学四年级')], default=1, help_text='年级', verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='head_portrait',
            field=models.ImageField(blank=True, default='head_portrait/v2-97573b50437aac7ae71b73de012470ef_720w.jpg', help_text='头像', max_length=200, upload_to='head_portrait/', verbose_name='头像'),
        ),
    ]
