# Generated by Django 3.0.4 on 2020-04-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200414_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='integral',
            field=models.IntegerField(default=0, help_text='积分', verbose_name='积分'),
        ),
    ]
