# Generated by Django 3.0.4 on 2020-04-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_integral'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sign',
            field=models.TextField(blank=True, help_text='个性签名', null=True, verbose_name='个性签名'),
        ),
    ]
