# Generated by Django 3.0.4 on 2020-04-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_chapter_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='title_pic',
            field=models.FileField(blank=True, upload_to='course/'),
        ),
    ]
