# Generated by Django 3.0.4 on 2020-03-22 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarIncidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='日历事件')),
                ('title', models.CharField(max_length=255, verbose_name='事件标题')),
                ('order', models.IntegerField(default=0, verbose_name='事件优先级')),
                ('details', models.TextField(blank=True, null=True, verbose_name='内容')),
            ],
            options={
                'verbose_name': '日历事件',
                'verbose_name_plural': '日历事件',
            },
        ),
    ]
