# Generated by Django 3.0.4 on 2020-04-14 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendar_incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarincidents',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建事件者'),
            preserve_default=False,
        ),
    ]
