# Generated by Django 3.0.4 on 2020-04-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='问卷名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='问卷介绍')),
                ('degree', models.IntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], default=1, help_text='难度', verbose_name='难度')),
                ('type', models.IntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], default=1, help_text='难度', verbose_name='难度')),
                ('is_hot', models.BooleanField(default=False, help_text='首页是否被展示', verbose_name='是否火热')),
                ('is_visible', models.BooleanField(default=False, help_text='课程不再被展示', verbose_name='是否可见')),
            ],
            options={
                'verbose_name': '问卷',
                'verbose_name_plural': '问卷',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='问题题目')),
                ('right_key', models.CharField(max_length=2, verbose_name='问题答案')),
                ('key_a', models.CharField(max_length=255, verbose_name='选项a')),
                ('key_b', models.CharField(max_length=255, verbose_name='选项b')),
                ('key_c', models.CharField(max_length=255, verbose_name='选项c')),
                ('key_d', models.CharField(max_length=255, verbose_name='选项d')),
                ('questionnaire', models.ManyToManyField(to='questionnaire.Questionnaire')),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
            },
        ),
    ]
