# Generated by Django 3.0.4 on 2020-04-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='number',
            field=models.IntegerField(default=4, help_text='题目数量', verbose_name='题目数量'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='type',
            field=models.IntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], default=1, help_text='类型', verbose_name='类型'),
        ),
    ]
