# Generated by Django 3.0.4 on 2020-04-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20200416_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionnaire',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question',
            field=models.ManyToManyField(to='questionnaire.Question'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='type',
            field=models.IntegerField(choices=[(1, '免费'), (2, '会员')], default=1, help_text='类型', verbose_name='类型'),
        ),
    ]
