# Generated by Django 3.0.4 on 2020-03-22 13:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='房间名称')),
                ('order', models.IntegerField(default=0, verbose_name='聊天房间优先级')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '日历事件',
                'verbose_name_plural': '日历事件',
            },
        ),
        migrations.CreateModel(
            name='ChatContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.TextField(blank=True, null=True, verbose_name='发送内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chat.ChatRoom', verbose_name='发送房间')),
                ('chat_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
