# Generated by Django 3.0.4 on 2020-04-14 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatcontent',
            options={'verbose_name': '聊天内容', 'verbose_name_plural': '聊天内容'},
        ),
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': '聊天房间', 'verbose_name_plural': '聊天房间'},
        ),
    ]
